"""Configuration and evidence parsing for y-cruncher 0.8.7's component stress tester.

The schema is generated by the upstream tester's Save Configuration command.
Parse the whole invocation, never just a tail that could discard an earlier error.
"""

import re
from collections import Counter, deque

TESTS = ("SFTv4", "SNT", "SVT", "FFTv4", "N63", "VT3")
ALIASES = {"NTT63": "N63", "VSTv3": "VT3"}
ANSI = re.compile(r"\x1b\[[0-?]*[ -/]*[@-~]")
PASSED = re.compile(r"^Running (\w+):\s*Passed\b")
ALLOCATION = re.compile(r"^\s*Core\s+(\d+):\s+([\d.,]+)\s+[KMGT]iB\s+node\s+(\d+)")
FAULT = re.compile(
    r"Test Failed|Tests Failed|Stress test failed|StressTestFailedException|"
    r"Error\(s\) encountered on logical core|"
    r"(?:checksum|value|bottom word) mismatch|Modular Redundancy Check Failed|"
    r"Running \w+:\s*(?:Failed|Error)", re.I)
ERROR = re.compile(r"\b(?:error|errors|exception|failed|failure|unsupported|unavailable)\b", re.I)


def configuration(cores, memory_mib, seconds):
    if not cores or memory_mib < 64 or seconds < 1:
        raise ValueError("y-cruncher needs CPU cores, at least 64 MiB and a positive duration")
    return {"Action": "StressTest", "StressTest": {
        "AllocateLocally": True,
        "LogicalCores": [str(c) for c in cores],
        "TotalMemory": memory_mib * 2**20,
        # Leave room for at least two complete rotations, including on short runs.
        "SecondsPerTest": min(120, max(1, seconds // (2 * len(TESTS)))),
        "SecondsTotal": seconds,
        "StopOnError": True,
        "Tests": list(TESTS),
    }}


def read_evidence(path, offset=0):
    passed, allocated, nodes = Counter(), set(), set()
    faults, errors, tail = [], [], deque(maxlen=12)
    finished, version = False, ""
    with open(path, "rb") as fh:
        fh.seek(offset)
        for raw in fh:
            line = ANSI.sub("", raw.decode("utf-8", "replace")).strip()
            if not line:
                continue
            tail.append(line[:500])
            if line.startswith("y-cruncher v"):
                version = line
            match = PASSED.match(line)
            if match:
                tag = ALIASES.get(match[1], match[1])
                passed[tag] += 1
            match = ALLOCATION.match(line)
            if match and float(match[2].replace(",", "")) > 0:
                allocated.add(int(match[1]))
                nodes.add(int(match[3]))
            if FAULT.search(line) and len(faults) < 25:
                faults.append(line[:500])
            # "Stop on Error: Enabled" is a setting, not an error.
            elif ERROR.search(line) and "Stop on Error:" not in line and len(errors) < 25:
                errors.append(line[:500])
            if line == "Test Finished. Waiting for threads to terminate...":
                finished = True
    return {"version": version, "passed": dict(passed), "allocated_cores": sorted(allocated),
            "allocation_nodes": sorted(nodes), "finished": finished,
            "faults": faults, "errors": errors, "tail": list(tail)}


def coverage_gaps(evidence, cores, seconds, elapsed, rc):
    gaps = []
    if rc != 0:
        gaps.append(f"Workload did not exit normally (exit code {rc})")
    if not evidence["finished"]:
        gaps.append("Missing normal completion marker")
    missing = [tag for tag in TESTS if evidence["passed"].get(tag, 0) < 1]
    if missing:
        gaps.append("No successful test result for: " + ", ".join(missing))
    missing_cores = sorted(set(cores) - set(evidence["allocated_cores"]))
    if missing_cores:
        gaps.append("No memory allocation evidence for cores: " + ", ".join(map(str, missing_cores)))
    if elapsed < seconds * 0.9:
        gaps.append(f"Workload ended early ({elapsed:.1f}s of {seconds}s)")
    gaps.extend(evidence["errors"])
    return gaps
